### ISSUE TITLE
What level of product manager does this guidance support?

### ISSUE THREAD

**Issue by stevenjmesser** [alphagov/Product-Managers-Learn-By-Doing#1]
I had thought that this guidance was originally developed to support associate product managers but can't see any mention of them. Is that right?

**Comment by JonForman** [comment]
The guidance is intended to support associate product managers in that it describes what we expect them to be able to do, as successful product managers. They can use this list to judge areas where they still need to grow, and steer their development with these examples of the 'what'.

**Comment by stevenjmesser** [comment]
OK, that makes sense, and I suppose it also supports anyone new to product management, regardless of being tagged with the 'associate' level.
