### ISSUE TITLE
Separation of activities and experiences into several files feels complicated

### ISSUE THREAD

**Issue by scottcolfer** [alphagov/Product-Managers-Learn-By-Doing#2]
Three observations:
- there are a lot of files
- I *think* that most people are initially more interested in the learning experiences/activities than the skills they link with, but readers need to engage with the skills before they can access the learning experiences/activities
- some of the learning experiences/activities overlap several skills (e.g. user focus and problem ownership activities are very similar).

_Based on the above, I wonder if a single file containing a single list of activities/experiences could be easier to use? It could be a table with the experience - bit of discussion of the experience - and skills its most likely to link with?_

**Comment by stevenjmesser** [comment]
Do we have any evidence of how people would put these documents to use which could inform the information architecture?

**Comment by scottcolfer** [comment]
We've been testing them at MOJ for the last three months, with our 12 associate product managers and their managers. Anecdotal feedback on the existing spreadsheet has been that it's complicated to use, with a lot of data to parse to figure out how to use it. The intent behind the initial point of contact seems to be to see the activities/experiences as simply/cleanly as possible. Reviewing this repo in light of the feedback received is what led to this issue.

_One specific piece of feedback on the current spreadsheet was around accessibility for people with dyslexia: they found the current amount of text and complicated nature of the structure difficult to engage with. They said they'd appreciate a simpler structure, with less text to engage with if possible. It'd be great to use this feedback to inform this repo, too_

**Comment by stevenjmesser** [comment]
That's interesting, I wonder whether a single file would create a simpler structure with less text to engage with. I'm no expert on that side of things, it's possible that one of the content designers at GDS would be able to provide good guidance on that.

**Comment by scottcolfer** [comment]
It's useful to say - I'm not invested in the single file as the only was to improve this - but am invested in solving the apparent problem of the current format being complicated :)

So:
- interested to hear feedback from others on their use of these activities/experience
- very interested to get guidance from content specialists

**Comment by JonForman** [comment]
Hi Gents, I've simplified the list of activities and experiences, and skill descriptions into tables and incorporated them into the single readme file.

Let me know your thoughts.

I'm also keen to get some input from a content designer, but think this is still a good improvement. I'm hoping the blog post will come out next week.

**Comment by scottcolfer** [comment]
Thanks for this Jon, appreciate it.
I've just shared with the APMs and their managers on Slack for feedback and will promote again in Friday's weeknotes.

**Comment by JonForman** [comment]
Thanks Scott. 

I’m going to close this issue for now Gents. May open something different around review by a content designer.
